hecommerce/account/urls.py
from django.urls import path
from.views import (
    signup_view,
    login_view,
    logout_view,
    VerificationView,
    superuser_login_view
    
)

app_name = "account"

urlpatterns = [
    path('login/',login_view,name="log_in"),
    path('admin-login',superuser_login_view,name="superuserlogin"),
    path('signup/',signup_view,name="sign_up"),
    path('logout/',logout_view,name="log_out"),
    path('activate/<uidb64>/<token>',VerificationView.as_view(),name="activate")
    
]

hecommerce/core/urls.py
from django.urls import path,re_path
from.views import(
    HomeView,
    ProductDetailView,
    add_to_cart,
    Order_Summary,
    remove_single_item_from_cart,
    remove_from_cart,
    CheckOutView,
    order_snippet_view,
    veiw_ordered_items_lists,
    notifications,
    displayCategory
)

app_name="core"

urlpatterns = [
    path('', HomeView.as_view(),name="productlists"),
    path('order-summary/',Order_Summary.as_view(),name="order-summary"),
    path('check-out/',CheckOutView.as_view(),name="check-out"),
    path('order-snippet/',order_snippet_view,name="order-snippet"),
    path('notifications/',notifications,name="notifications"),
    path('add-to-cart/<slug>/',add_to_cart,name="add-to-cart"), 
    path('remve-from-cart/<slug>/',remove_from_cart,name="remove-from-cart"),
    path('remove-single-item-from-cart/<slug>/',remove_single_item_from_cart,name="remove-single-item-from-cart"),    
    path('view-ordered-items/<slug>/',veiw_ordered_items_lists,name="vieworderedlists"),
    path('category/<category>',displayCategory,name="display-category"),
    re_path(r'(?P<slug>[\w-]+)/$',ProductDetailView.as_view(),name="productdetail"),
    
]

hecommerce/hecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myadmin/',include('myadmin.urls')),
    path('account/',include('account.urls')),
    path('',include('core.urls')),
    
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

hecommerce/myadmin/urls.py
from django.urls import path,re_path
from.views import(
    UploadProduct,
    PendingOrders,
    pending_order_detail_view,
    pending_order_confirm,
    view_ordered,
    pending_order_reject,
    UpdateProductList,
    UpdateProduct,
    view_ordered_detail,
    newsletterlists,
    updateNewsLetter
)

app_name = "myadmin"
urlpatterns = [
    path('admins/',UploadProduct.as_view(),name="upload-product"),
    path('pending-orders/',PendingOrders.as_view(),name="pendingorders"),    
    path('view-ordered/',view_ordered,name="viewordered"),
    path('news-letter-lists',newsletterlists,name="newsletterlists"),
    path('update-newsletter/<id>',updateNewsLetter,name="updatenewsletter"),
    path('ordered_dtail/<slug>',view_ordered_detail,name="ordered-detail"),
    path('update-product/',UpdateProductList.as_view(),name="updateproductlist"),
    path('update-product/<slug>',UpdateProduct.as_view(),name="updateproduct"),
    path('pending-orders-detail/<slug>/',pending_order_detail_view,name="pendingdetail"),
    path('pending-orders-confirm/<slug>/',pending_order_confirm,name="pendingorderconfirm"),
    path('pending-orders-reject/<slug>',pending_order_reject,name="pendingorderreject")
    
]

hecommerce/core/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse

CATEGORY_CHOICES = (
    ('E', 'Electronic'),
    ('S', 'Shirt'),
    ('U', 'Utility')
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger'),
    ('N', 'None')
)

# Create your models here.
class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=10)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    product_quantity = models.IntegerField(null=False,blank=False,default=0)
    slug = models.SlugField()
    description = models.TextField()
    status = models.BooleanField(default=True)
    image = models.ImageField()
    
    def __str__(self):
        return self.title
    
    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug': self.slug
        })       
        
    def title_split(self):
        return self.title[:39] + '...'
    
    
class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    
    def __str__(self):
        return f"{self.quantity} of {self.item.title}"
    
    def get_total_item(self):
        return self.quantity
    
    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_final_price(self):
        return self.get_total_item_price()

class Order(models.Model):
    def get_ref_code():
        last_ref_code = Order.objects.all().order_by('id').last()
        if not last_ref_code:
            return 'INV-000-1'
        invoice_no = last_ref_code.ref_code
        invoice_int = int(invoice_no.split('-')[2])
        new_invoice_int = invoice_int + 1
        new_invoice_no = 'INV-000-' + str(new_invoice_int)
        return new_invoice_no


    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20, blank=True, null=True,default=get_ref_code)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    pending = models.BooleanField(default=True)
    payment = models.ForeignKey('Payment',on_delete=models.SET_NULL, blank=True, null=True)
    
    def __str__(self):
        return self.user.username  
    
    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        return total
    
    def get_item_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_total_item()
        return total
        
    
    
CITIES_STATE = (
    ('kachin','Kachin'),
    ('kaya','Kaya'),
    ('Kayin','Kayin'),
    ('chin','Chin'),
    ('mon','Mon'),
    ('yangon','Yangon'),
    ('naypyitaw','Nay Pyi Taw'),
    ('Mandalay','Mandalay'),
    ('rakhine','Rakhine')
    
)

PAYMENT_CHOICES = (
    ('cbpay','CB Pay'),
    ('kbzpay','KBZ Pay'),
    ('ayapay','AYA Pay'),
    ('cbbank','CB Bank Transfer'),
    ('kbzbank','KBZ Bank Transfer'),
    ('ayabank','AYA Bank Transfer')
)

class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    cities_state = models.CharField(choices=CITIES_STATE, max_length=11)
    
    def __str__(self):
        return self.user.username  
    
class Payment(models.Model):
    def get_ref_code():
        last_ref_code = Payment.objects.all().order_by('id').last()
        if not last_ref_code:
            return 'INV-000-1'
        invoice_no = last_ref_code.payment_ref_code
        invoice_int = int(invoice_no.split('-')[2])
        new_invoice_int = invoice_int + 1
        new_invoice_no = 'INV-000-' + str(new_invoice_int)
        return new_invoice_no
    
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    payment_opition =  models.CharField(choices=PAYMENT_CHOICES,max_length=20)
    payment_date = models.DateTimeField(auto_now_add=True)
    payment_img = models.ImageField()
    payment_ref_code = models.CharField(max_length=20, blank=True, null=True,default=get_ref_code)
    
    
    def __str__(self):
        return self.user.username
    
class Notification(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    notification_title = models.CharField(max_length=100,blank=True,null=True)    
    opened = models.BooleanField(default=False)
    success_fail = models.BooleanField(default=True)
    
    def __str__(self):
        return self.user.username
    
class NewsLetter(models.Model):
    imge = models.ImageField()
    title = models.CharField(max_length=100,null=True,blank=True)
    date = models.DateField(auto_now_add=True)
    

    

hecommerce/core/forms.py
from django import forms

CITIES_STATE = (
    ('kachin','Kachin'),
    ('kaya','Kaya'),
    ('Kayin','Kayin'),
    ('chin','Chin'),
    ('mon','Mon'),
    ('yangon','Yangon'),
    ('naypyitaw','Nay Pyi Taw'),
    ('Mandalay','Mandalay'),
    ('rakhine','Rakhine')    
)

PAYMENT_CHOICES = (
    ('cbpay','CB Pay'),
    ('kbzpay','KBZ Pay'),
    ('ayapay','AYA Pay'),
    ('cbbank','CB Bank Transfer'),
    ('kbzbank','KBZ Bank Transfer'),
    ('ayabank','AYA Bank Transfer')
)


class AddressForm(forms.Form):
    address = forms.CharField( widget=forms.TextInput(
        attrs= {
            'class':"form-control",
            'placeholder': "1234 Main St",
            'id':"address"
        }
        ), required=True)
    address_2 = forms.CharField( widget=forms.TextInput(
        attrs= {
            'class':"form-control",
            'placeholder': "Apartment or suite",
            'id':"address-2"
        }
        ), required=True)
    cities_state = forms.ChoiceField(
        widget=forms.Select(
                 attrs ={
            'class': 'custom-select d-block w-100'
        }),choices = CITIES_STATE,required=True,      
    )

class PaymentForm(forms.Form):

    payment_opition = forms.ChoiceField(
        widget=forms.Select(
            attrs= {
                'class': 'custom-select d-block w-100' }),choices = PAYMENT_CHOICES,required=True
    )
    file = forms.ImageField(
        widget=forms.FileInput(
            attrs={
            'class':'custom-file-input',
            'id': 'inputGroupFile01'
            }
        ),
        required=True)
    

hecommerce/core/templates/navbar.html
{% load count-cart-item %}

<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">        
      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="{% url 'core:productlists' %}">
        <strong class="blue-text">H-Ecommerce</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
      {% if request.user.is_authenticated %}
        
        {% if request.user.is_superuser %}
        
          <li class="nav-item active">
            <a class="nav-link waves-effect" href="{% url 'core:productlists' %}">Dashboard
              <span class="sr-only">(current)</span>
            </a>
          </li>
           {% else %}

           <li class="nav-item active">
            <a class="nav-link waves-effect" href="{% url 'core:productlists' %}">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>

           <li class="nav-item dropdown ml-3">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Categories
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'core:display-category' category='E'%}">Electronic</a>
              <a class="dropdown-item" href="{% url 'core:display-category' category='S'%}">Shirt</a>
              <a class="dropdown-item" href="{% url 'core:display-category' category='U'%}">Utility</a>
            </div>
          </li>
        {% endif %}        
      {% endif %}
        
        </ul>
        <!-- Right -->

        <ul class="navbar-nav nav-flex-icons">
        {% if request.user.is_authenticated %}
        
        {% if request.user.is_superuser %}
        {% else %}
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'core:order-summary' %}">
            <span class="badge red z-depth-1 mr-1"> {{request.user|cart_item_count}} </span>                     
            <i class="fas fa-shopping-cart"></i>
            <span class="clearfix d-none d-sm-inline-block"> Cart </span>
          </a>
        {% endif %}
          
          </li>
          
        {% endif %}
                  
          {% if request.user.is_authenticated %} 
          
            {% if request.user.is_superuser %}
              <li class="nav-item">
                <a href="" class="nav-link"> {{request.user}}    </a>
              </li>
              <li class="nav-item">
                <form action="{% url 'account:log_out' %}" method="POST">
                  {% csrf_token %}
                   <input type="submit" value="Log out" class="nav-link border border-light rounded waves-effect">                   
                </form>
              </li>

              {% else %}
              
              <li class="nav-item">
                
                  <a href="{% url 'core:notifications' %}" class="nav-link  mybg">
                    
                      <i class="far fa-bell"></i> <span class="badge badge-light ml-2">{{request.user|notification_count}}</span>
                    
                  </a>
              </li>
              <li class="nav-item dropdown">
                <a href="" class="nav-link border border-light rounded waves-effect dropdown-toggle"
                  id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="far fa-user mr-2"></i>{{user}} 
                </a> 
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a href="{% url 'core:order-snippet' %}" class="dropdown-item">Order Snippet</a>
                </div>                   
              </li>

              <li class="nav-item ml-3">
                <form action="{% url 'account:log_out' %}" method="POST">
                  {% csrf_token %}
                   <input type="submit" value="Log out" class="nav-link border border-light rounded waves-effect"> 
                  
                </form>
                
              </li>
            {% endif %}                  

          {% else %}

          <li class="nav-item">
            <a href="{% url 'account:log_in' %}" class="nav-link border border-light rounded waves-effect"
              >
              <i class="fas fa-sign-in-alt mr-2"></i>Log in
            </a>                    
          </li>
          <li class="nav-item ml-2">
            <a href="{% url 'account:sign_up' %}" class="nav-link border border-light rounded waves-effect"
              >
              <i class="fas fa-user-plus mr-2"></i>Sign Up
            </a>                    
          </li>
          {% endif %}
          
        </ul>

      </div>

    </div>
  </nav>

hecommerce/core/templates/order-summary.html
{% extends 'base_layout.html' %}

{% block content %}    

  <div class="table-responsive mt-3">
        <h1 class="center mt-5">Order Summary</h1>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Item Title</th>
        <th scope="col">Price</th>
        <th scope="col">Quantity</th>
        <th scope="col">Total Item Price</th>
      </tr>
    </thead>
    <tbody>
               
          {% for order_item in object.items.all %}
          <tr> 
            <th scope="row">{{forloop.counter}}</th>
            <td>{{order_item.item.title}}</td>
            <td>{{order_item.item.price}}</td>
            <td>
              <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}">
                <i class="fas fa-minus mr-2"></i>
              </a>
               {{order_item.quantity}} 
               
              {% if order_item.item.product_quantity == 0 %}
              <p> This product quantity is out of stock.</p>
              {% else %}
              <a href="{% url 'core:add-to-cart' order_item.item.slug%}">
                <i class="fas fa-plus ml-2"></i></td>
               </a>
              {% endif %}
              

            <td> {{ order_item.get_total_item_price}} </td>
            <td>
              <a href="{% url 'core:remove-from-cart' order_item.item.slug %}" class="btn btn-danger btn-sm">
                Remove
              </a>
            </td>
          </tr>
          {% endfor %}        
 
      

      <tr>
        <td colspan="4"><b>Order Total</b></td>
        <td><b>${{ object.get_total }}</b></td>
      </tr>
      <tr>
        <td colspan="5">
        <a class='btn btn-warning float-right ml-2' href='/check-out/'>Proceed to checkout</a>
        <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
        </td>
    </tr>
      
    </tbody>
  </table>
</div>
{% endblock content %}
    

hecommerce/core/templates/product_lists.html
{% extends 'base_layout.html' %}
{% block content %}
{% load count-cart-item %}

{% if request.user.is_authenticated %} <!-- Authenticated Start -->
    
     {% if request.user.is_superuser %}  <!-- Super User Start -->
  <div style="height:600px;">
    
    <div class="row">
      <div class="col-md-4 custom-card mt-3 ml-3" style="background-color: #697FEF">
        <div class="row">
          <div class="col-lg-12 text-center mt-3 text-white">
            <h1 class="">Inventory</h1>
          </div>
          
        </div>
        <div class="row">
          <div class="col-lg-12 text-center mt-2 mb-3 text-white">
            <h1 class="">{{items_count}}</h1>
          </div>
        </div>
      </div>   
      
      <div class="col-md-4 custom-card ml-3 mt-3" style="background-color: #0093D5">
        <div class="row">
          <div class="col-lg-12 text-center mt-3 text-white">
            <h1 class="">Pending Ordered</h1>
          </div>
          
        </div>
        <div class="row">
          <div class="col-lg-12 text-center mt-2 mb-3 text-white">
            <h1 class="">{{order_count}}</h1>
          </div>
        </div>
      </div>  

      <div class="col-md-3 custom-card ml-3 mt-3" style="background-color: #EF6969">
        <div class="row">
          <div class="col-lg-12 text-center mt-3 text-white">
            <h1 class=""> Ordered</h1>
          </div>
          
        </div>
        <div class="row">
          <div class="col-lg-12 text-center mt-2 mb-3 text-white">
            <h1 class="">{{ordered_count}}</h1>
          </div>
        </div>
      </div> 
    </div>   
    
    <div class="row mb-5 mt-5">
      <div class="col-lg-4">
        <h3>
          Product
        </h3>
          <div class="row">
            
            <div class="col-lg-5">
              <a href="{% url 'myadmin:upload-product' %}" class=>
                <div class="custom-card text-center">
                  <i class="fas fa-upload fa-3x pt-3 pb-3 text-white"></i>
                  <span>
                    <p class="pb-2 text-dark">Upload Product</p>
                  </span>
                </div>
              </a>
            </div>

            <div class="col-lg-5">
              <a href="{% url 'myadmin:updateproductlist' %}" class=>
                <div class="custom-card text-center">
                  <i class="far fa-edit fa-3x pt-3 pb-3 text-white"></i>
                  <span>
                    <p class="pb-2 text-dark">Update Product</p>
                  </span>
                </div>
              </a>
            </div>

          </div>
        
      </div>

      <div class="col-lg-4">
        <h3>
          Orders
        </h3>
          <div class="row">
            
            <div class="col-lg-5">
              <a href="{% url 'myadmin:pendingorders' %}" class=>
                <div class="custom-card text-center">
                  <i class="far fa-clock fa-3x pt-3 pb-3 text-white"></i>

                  <span>
                    <p class="pb-2 text-dark">Pending Orders</p>
                  </span>
                </div>
              </a>
            </div>

            <div class="col-lg-5">
              <a href="{% url 'myadmin:viewordered' %}" class=>
                <div class="custom-card text-center">
                  <i class="fas fa-border-all fa-3x pt-3 pb-3 text-white"></i>
                  <span>
                    <p class="pb-2 text-dark">View Ordered</p>
                  </span>
                </div>
              </a>
            </div>

          </div>
        
      </div>

      <div class="col-lg-4">
        <h3>
          CMS
        </h3>
          <div class="row">
            
            <div class="col-lg-5">
              <a href="{% url 'myadmin:newsletterlists' %}" class=>
                <div class="custom-card text-center">
                  <i class="fas fa-sliders-h fa-3x pt-3 pb-3 text-white"></i>
                  

                  <span>
                    <p class="pb-2 text-dark">NewsLetters</p>
                  </span>
                </div>
              </a>
            </div>

          </div>
        
      </div>

    </div>
  </div>

      {% else %} <!-- Super User End -->
      
      <!-- This is login user which is activated view -->
  <div class="container-fluid"> 
    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
        
        <div class="carousel-item active">
          <img class="d-block w-100" src="{{newsletter.imge.url}}" alt="slide">
        </div>

        
        {% for nl in newsletters %}
        <div class="carousel-item">
          <img class="d-block w-100" src="{{nl.imge.url}}" alt="slide">
        </div>
        {% endfor %}
        
      </div>
      <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>
      
  
  <!--Grid row-->
 <div class="row wow fadeIn mt-2">
  
  {% for item in object_list %}
  <div class="col-lg-3 col-md-6 mb-4 mt-5"> <!--Grid column-->

    <!--Card-->
    <div class="card">
      <!--Card image-->
      <div class="view overlay">
        <img src="{{item.image.url}}" class="card-img-top rounded"
          alt="{{item.slug}}" >
        <a>
          <div class="mask rgba-white-slight"></div>
        </a>
      </div>
      <!--Card image-->

      <!--Card content-->
      <div class="card-body text-center">
        <!--Category & Title-->
        <a href="{{item.slug}}" class="grey-text">
          <h5>
          {{item.title_split}}
          </h5>
        </a>
        <h5>
          
            <a href="{{item.slug}}" class="dark-grey-text" style="font-size: 18px;">{{item.get_category_display}}
              {% if item.get_label_display == 'danger' %}
              <span class="badge badge-pill {{item.get_label_display}}-color">NEW</span>
              {% elif item.get_label_display == 'secondary' %}
              <span class="badge badge-pill {{item.get_label_display}}-color">Best Seller</span>
              {% elif item.get_label_display == 'primary' %}
              <span class=""></span>
              {% endif %}
            </a>
          
        </h5>

        <h4 class="font-weight-bold blue-text">
          <strong>${{item.price}}</strong>
        </h4>

      </div>
      <!--Card content-->

    </div>
    <!--Card-->

  </div>
  <!--Grid column-->
  {% endfor %} 

</div>
<!--Grid row-->

<!--Pagination-->

{% if is_paginated %}

<nav class="d-flex justify-content-center wow fadeIn">
<ul class="pagination pg-blue">
  
  {% if page_obj.has_previous %}
    <!--Arrow left-->
    <li class="page-item ">
      <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
        <span class="sr-only">Previous</span>
      </a>
    </li>
  {% endif %}
  <li class="page-item active">
    <a class="page-link" href="?page={{page_obj.next_page_number}}">{{page_obj.next_page_number}}
      <span class="sr-only">(current)</span>
    </a>
  </li>
  
  {% if page_obj.has_next %}
  <li class="page-item">
    <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
      <span aria-hidden="true">&raquo;</span>
      <span class="sr-only">Next</span>
    </a>
  </li>
  {% endif %}
    
  
</ul>
</nav>
<!--Pagination-->

    {% endif %}
      
{% endif %}
  
{% else %}

<div class="container-fluid"> 
  <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      
      <div class="carousel-item active">
        <img class="d-block w-100" src="{{newsletter.imge.url}}" alt="slide">
      </div>

      
      {% for nl in newsletters %}
      <div class="carousel-item">
        <img class="d-block w-100" src="{{nl.imge.url}}" alt="slide">
      </div>
      {% endfor %}
      
    </div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>
<div class="row wow fadeIn mt-2">
  
  {% for item in object_list %}
  <div class="col-lg-3 col-md-6 mb-4 mt-5"> <!--Grid column-->

    <!--Card-->
    <div class="card">
      <!--Card image-->
      <div class="view overlay">
        <img src="{{item.image.url}}" class="card-img-top rounded"
          alt="{{item.slug}}" > 
        <a>
          <div class="mask rgba-white-slight"></div>
        </a>
      </div>
      <!--Card image-->

      <!--Card content-->
      <div class="card-body text-center">
        <!--Category & Title-->
        <a href="{{item.slug}}" class="grey-text">
          <h5>{{item.title}}</h5>
        </a>
        <h5>
          <strong>
            <a href="{{item.slug}}" class="dark-grey-text">{{item.get_category_display}}
              
              {% if item.get_label_display == 'danger' %}
              <span class="badge badge-pill {{item.get_label_display}}-color">NEW</span>
              {% elif item.get_label_display == 'secondary' %}
              <span class="badge badge-pill {{item.get_label_display}}-color">Best Seller</span>
              {% elif item.get_label_display == 'primary' %}
              <span class=""></span>
              {% endif %}
                
              
            </a>
          </strong>
        </h5>

        <h4 class="font-weight-bold blue-text">
          <strong>{{item.price}}</strong>
        </h4>

      </div>
      <!--Card content-->

    </div>
    <!--Card-->

  </div>
  <!--Grid column-->
  {% endfor %} 

</div>
<!--Grid row-->

<!--Pagination-->

{% if is_paginated %}

<nav class="d-flex justify-content-center wow fadeIn">
<ul class="pagination pg-blue">
  
  {% if page_obj.has_previous %}
    <!--Arrow left-->
    <li class="page-item ">
      <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
        <span class="sr-only">Previous</span>
      </a>
    </li>
  {% endif %}
  <li class="page-item active">
    <a class="page-link" href="?page={{page_obj.next_page_number}}">{{page_obj.next_page_number}}
      <span class="sr-only">(current)</span>
    </a>
  </li>
  
  {% if page_obj.has_next %}
  <li class="page-item">
    <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
      <span aria-hidden="true">&raquo;</span>
      <span class="sr-only">Next</span>
    </a>
  </li>
  {% endif %}
    
  
</ul>
</nav>
<!--Pagination-->

    {% endif %}

{% endif %}


{% endblock %}

hecommerce/core/templates/subcategory.html
{% extends 'base_layout.html' %}

{% block content %}
{{error}}
<h1>This is {{items}}</h1>
    {% for item in items %}
        <h1>{{item.title}}</h1>
    {% endfor %}
{% endblock content %}