hecommerce/core/urls.py
from django.urls import path,re_path
from.views import(
    HomeView,
    ProductDetailView,
    add_to_cart,
    Order_Summary,
    remove_single_item_from_cart,
    remove_from_cart,
    CheckOutView,
    order_snippet_view,
    veiw_ordered_items_lists,
    notifications,
    displayCategory
)

app_name="core"

urlpatterns = [
    path('', HomeView.as_view(),name="productlists"),
    path('order-summary/',Order_Summary.as_view(),name="order-summary"),
    path('check-out/',CheckOutView.as_view(),name="check-out"),
    path('order-snippet/',order_snippet_view,name="order-snippet"),
    path('notifications/',notifications,name="notifications"),
    path('add-to-cart/<slug>/',add_to_cart,name="add-to-cart"), 
    path('remve-from-cart/<slug>/',remove_from_cart,name="remove-from-cart"),
    path('remove-single-item-from-cart/<slug>/',remove_single_item_from_cart,name="remove-single-item-from-cart"),    
    path('view-ordered-items/<slug>/',veiw_ordered_items_lists,name="vieworderedlists"),
    path('category/<category>',displayCategory,name="display-category"),
    re_path(r'(?P<slug>[\w-]+)/$',ProductDetailView.as_view(),name="productdetail"),
    
]

hecommerce/hecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myadmin/',include('myadmin.urls')),
    path('account/',include('account.urls')),
    path('',include('core.urls')),
    
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

hecommerce/myadmin/urls.py
from django.urls import path,re_path
from.views import(
    UploadProduct,
    PendingOrders,
    pending_order_detail_view,
    pending_order_confirm,
    view_ordered,
    pending_order_reject,
    UpdateProductList,
    UpdateProduct,
    view_ordered_detail,
    newsletterlists,
    updateNewsLetter
)

app_name = "myadmin"
urlpatterns = [
    path('admins/',UploadProduct.as_view(),name="upload-product"),
    path('pending-orders/',PendingOrders.as_view(),name="pendingorders"),    
    path('view-ordered/',view_ordered,name="viewordered"),
    path('news-letter-lists',newsletterlists,name="newsletterlists"),
    path('update-newsletter/<id>',updateNewsLetter,name="updatenewsletter"),
    path('ordered_dtail/<slug>',view_ordered_detail,name="ordered-detail"),
    path('update-product/',UpdateProductList.as_view(),name="updateproductlist"),
    path('update-product/<slug>',UpdateProduct.as_view(),name="updateproduct"),
    path('pending-orders-detail/<slug>/',pending_order_detail_view,name="pendingdetail"),
    path('pending-orders-confirm/<slug>/',pending_order_confirm,name="pendingorderconfirm"),
    path('pending-orders-reject/<slug>',pending_order_reject,name="pendingorderreject")
    
]

hecommerce/core/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse

CATEGORY_CHOICES = (
    ('E', 'Electronic'),
    ('S', 'Shirt'),
    ('U', 'Utility')
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger'),
    ('N', 'None')
)

# Create your models here.
class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=10)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    product_quantity = models.IntegerField(null=False,blank=False,default=0)
    slug = models.SlugField()
    description = models.TextField()
    status = models.BooleanField(default=True)
    image = models.ImageField()
    
    def __str__(self):
        return self.title
    
    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug': self.slug
        })       
        
    def title_split(self):
        return self.title[:39] + '...'
    
    
class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    
    def __str__(self):
        return f"{self.quantity} of {self.item.title}"
    
    def get_total_item(self):
        return self.quantity
    
    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_final_price(self):
        return self.get_total_item_price()

class Order(models.Model):
    def get_ref_code():
        last_ref_code = Order.objects.all().order_by('id').last()
        if not last_ref_code:
            return 'INV-000-1'
        invoice_no = last_ref_code.ref_code
        invoice_int = int(invoice_no.split('-')[2])
        new_invoice_int = invoice_int + 1
        new_invoice_no = 'INV-000-' + str(new_invoice_int)
        return new_invoice_no


    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20, blank=True, null=True,default=get_ref_code)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    pending = models.BooleanField(default=True)
    payment = models.ForeignKey('Payment',on_delete=models.SET_NULL, blank=True, null=True)
    
    def __str__(self):
        return self.user.username  
    
    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        return total
    
    def get_item_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_total_item()
        return total
        
    
    
CITIES_STATE = (
    ('kachin','Kachin'),
    ('kaya','Kaya'),
    ('Kayin','Kayin'),
    ('chin','Chin'),
    ('mon','Mon'),
    ('yangon','Yangon'),
    ('naypyitaw','Nay Pyi Taw'),
    ('Mandalay','Mandalay'),
    ('rakhine','Rakhine')
    
)

PAYMENT_CHOICES = (
    ('cbpay','CB Pay'),
    ('kbzpay','KBZ Pay'),
    ('ayapay','AYA Pay'),
    ('cbbank','CB Bank Transfer'),
    ('kbzbank','KBZ Bank Transfer'),
    ('ayabank','AYA Bank Transfer')
)

class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    cities_state = models.CharField(choices=CITIES_STATE, max_length=11)
    
    def __str__(self):
        return self.user.username  
    
class Payment(models.Model):
    def get_ref_code():
        last_ref_code = Payment.objects.all().order_by('id').last()
        if not last_ref_code:
            return 'INV-000-1'
        invoice_no = last_ref_code.payment_ref_code
        invoice_int = int(invoice_no.split('-')[2])
        new_invoice_int = invoice_int + 1
        new_invoice_no = 'INV-000-' + str(new_invoice_int)
        return new_invoice_no
    
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    payment_opition =  models.CharField(choices=PAYMENT_CHOICES,max_length=20)
    payment_date = models.DateTimeField(auto_now_add=True)
    payment_img = models.ImageField()
    payment_ref_code = models.CharField(max_length=20, blank=True, null=True,default=get_ref_code)
    
    
    def __str__(self):
        return self.user.username
    
class Notification(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    notification_title = models.CharField(max_length=100,blank=True,null=True)    
    opened = models.BooleanField(default=False)
    success_fail = models.BooleanField(default=True)
    
    def __str__(self):
        return self.user.username
    
class NewsLetter(models.Model):
    imge = models.ImageField()
    title = models.CharField(max_length=100,null=True,blank=True)
    date = models.DateField(auto_now_add=True)
    

    

hecommerce/myadmin/models.py
from django.db import models

# Create your models here.

hecommerce/myadmin/forms.py
from django import forms
from .models import models
from core.models import Item,NewsLetter

CATEGORY_CHOICES = (
    ('E', 'Electronic'),
    ('S', 'Shirt'),
    ('U', 'Utility')
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)

class UploadProductForm(forms.Form):
    title = forms.CharField( widget=forms.TextInput(
        attrs= {
            'class':"form-control",
            'placeholder': "Product Title Here",
            'id':"title"
        }
        ), required=True)
    price = forms.FloatField( widget=forms.TextInput(
        attrs= {
            'class':"form-control",
            'placeholder': "Price : eg 30.0",
            'id':"price"
        }
        ), required=True)

    product_quantity = forms.IntegerField( widget=forms.NumberInput(
        attrs={
            'class' : 'form-control',
            'placeholder': "Quantity : eg : 30",
            'id':"quantity"
        }
    )
    )
    category = forms.ChoiceField(
        widget=forms.Select(
                 attrs ={
            'class': 'custom-select d-block w-100'
        }),choices = CATEGORY_CHOICES,required=True,      
    )
    label = forms.ChoiceField(
        widget=forms.Select(
                 attrs ={
            'class': 'custom-select d-block w-100'
        }),choices = LABEL_CHOICES,required=True,      
    )
    slug = forms.CharField( widget=forms.TextInput(
        attrs= {
            'class':"form-control",
            'placeholder': "Slug Here",
            'id':"slug"
        }
        ), required=True)
    description = forms.CharField( widget=forms.Textarea(
        attrs= {
            'class':"form-control",
            'placeholder': "Product Description Here",
            'id':"product_description"
        }
        ), required=True)
    image = forms.ImageField(
        widget=forms.FileInput(
            attrs={
            'class':'custom-file-input',
            'id': 'inputGroupFile01',
            
           }
        ),
        required=True)
    
class UpdateForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = '__all__'
        
class AddNewsLetter(forms.ModelForm):
    class Meta:
        model = NewsLetter
        fields = '__all__'
    
  

hecommerce/myadmin/templates/dashboard.html
{% extends 'base_layout.html' %}


{% block content %}
<div class="row">
    <div class="col-md-4 custom-card mt-3 ml-3" style="background-color: #697FEF">
      <div class="row">
        <div class="col-lg-12 text-center mt-3 text-white">
          <h1 class="">Inventory</h1>
        </div>
        
      </div>
      <div class="row">
        <div class="col-lg-12 text-center mt-2 mb-3 text-white">
          <h1 class="">{{items_count}}</h1>
        </div>
      </div>
    </div>   
    
    <div class="col-md-4 custom-card ml-3 mt-3" style="background-color: #0093D5">
      <div class="row">
        <div class="col-lg-12 text-center mt-3 text-white">
          <h1 class="">Pending Ordered</h1>
        </div>
        
      </div>
      <div class="row">
        <div class="col-lg-12 text-center mt-2 mb-3 text-white">
          <h1 class="">{{order_count}}</h1>
        </div>
      </div>
    </div>  

    <div class="col-md-3 custom-card ml-3 mt-3" style="background-color: #EF6969">
      <div class="row">
        <div class="col-lg-12 text-center mt-3 text-white">
          <h1 class=""> Ordered</h1>
        </div>
        
      </div>
      <div class="row">
        <div class="col-lg-12 text-center mt-2 mb-3 text-white">
          <h1 class="">{{ordered_count}}</h1>
        </div>
      </div>
    </div> 
  </div>   
  
  <div class="row mb-5 mt-5">
    <div class="col-lg-4">
      <h3>
        Product
      </h3>
        <div class="row">
          
          <div class="col-lg-5">
            <a href="{% url 'myadmin:upload-product' %}" class=>
              <div class="custom-card text-center">
                <i class="fas fa-upload fa-3x pt-3 pb-3 text-white"></i>
                <span>
                  <p class="pb-2 text-dark">Upload Product</p>
                </span>
              </div>
            </a>
          </div>

          <div class="col-lg-5">
            <a href="{% url 'myadmin:updateproductlist' %}" class=>
              <div class="custom-card text-center">
                <i class="far fa-edit fa-3x pt-3 pb-3 text-white"></i>
                <span>
                  <p class="pb-2 text-dark">Update Product</p>
                </span>
              </div>
            </a>
          </div>

        </div>
      
    </div>

    <div class="col-lg-4">
      <h3>
        Orders
      </h3>
        <div class="row">
          
          <div class="col-lg-5">
            <a href="{% url 'myadmin:pendingorders' %}" class=>
              <div class="custom-card text-center">
                <i class="far fa-clock fa-3x pt-3 pb-3 text-white"></i>

                <span>
                  <p class="pb-2 text-dark">Pending Orders</p>
                </span>
              </div>
            </a>
          </div>

          <div class="col-lg-5">
            <a href="{% url 'myadmin:viewordered' %}" class=>
              <div class="custom-card text-center">
                <i class="fas fa-border-all fa-3x pt-3 pb-3 text-white"></i>
                <span>
                  <p class="pb-2 text-dark">View Ordered</p>
                </span>
              </div>
            </a>
          </div>

        </div>
      
    </div>

    <div class="col-lg-4">
      <h3>
        CMS
      </h3>
        <div class="row">
          
          <div class="col-lg-5">
            <a href="{% url 'myadmin:newsletterlists' %}" class=>
              <div class="custom-card text-center">
                <i class="fas fa-sliders-h fa-3x pt-3 pb-3 text-white"></i>
                

                <span>
                  <p class="pb-2 text-dark">NewsLetters</p>
                </span>
              </div>
            </a>
          </div>

        </div>
      
    </div>

  </div>
{% endblock content %}
    

hecommerce/myadmin/templates/news-letter-lists.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>New Letter List</h1>

<div class="row" style="height:570px">
    {% for newletter in newsletters %}
    <div class="col-lg-4">        
        <a href="{% url 'myadmin:updatenewsletter' id=newletter.id %}" style="color: black;">
            <!-- Card -->
            <div class="card card-cascade wider">
                <!-- Card image -->
                <img src="{{newletter.imge.url}}" alt="" class="img-fluid mx-auto d-block" style="width: 250px;">
            
                <!-- Title -->
                <h2 class="card-header-title mb-3">{{newletter.title}}</h2>
                <!-- Text -->
                <p class="mb-0"><i class="fas fa-calendar mr-2"></i>{{newletter.date}}</p>
            </div>
            <!-- Card -->
        </a>
</div>
    {% endfor %}
</div>
{% endblock %}

hecommerce/myadmin/templates/ordered-detail.html
{% extends 'base_layout.html' %}


{% block content %}
<h1>Ordered detail </h1>      
  
<div class="row">
  {% for order in orders %}
  
    <div class="col-lg-8">           
      <button type="button" class="btn btn-primary">{{order.ref_code}}</button>
      
        <div class="table-responsive">
          <table class="table">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Product Name</th>
                <th scope="col">Quantity</th>
                <th scope="col">Price</th>
              </tr>
            </thead>
            <tbody>
              {% for order_item in order.items.all %}
              <tr>
               
                
                <th scope="row">{{forloop.counter}}</th>
                <td>{{order_item.item.title}}</td>
                <td>{{order_item.get_total_item}}</td>
                <td>{{order_item.item.price}}</td>
                       
              </tr>    
              {% endfor %} 
              <tr>
                {% for my_order in orders %}
                <td colspan="3"><b>Order Total</b></td>
                <td><b>${{ my_order.get_total }}</b></td>
                
                {% endfor %}
                
              </tr>
            </tbody>
          </table>
        </div>
          
        
    </div>

    <div class="col-lg-4">
      <img src="{{order.payment.payment_img.url}}" alt="" width="500px" height="250px">
    </div>
    
    {% endfor %}

</div>
{% endblock content %}
    

hecommerce/myadmin/templates/ordered.html
{% extends 'base_layout.html' %}

{% block content %}

<div class="table-responsive text-nowrap" style="height:600px;">

    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Invoice No</th>
          <th scope="col">Customer Name</th>
          <th scope="col">Quantity</th>          
          <th scope="col">Total</th>
          <th scope="col">Payment Opition</th>          
          <th scope="col"></th>         
        </tr>
      </thead>
      <tbody>
        {% for order in orders %}
          <tr>            
            <th scope="row">{{forloop.counter}}</th>
                <td>
                  {{order.ref_code}}
                </td>  

                <td>
                {{order.user}}
                </td>

                <td>{{order.get_item_total}}</td>
                <td>{{order.get_total}}</td>     
                
                <td> 
                  {{order.payment.payment_opition}}       
                </td>  

                <td>
                  <a href="{% url 'myadmin:ordered-detail' slug=order.ref_code %}">
                  View Detail
                  </a>
                </td>
                        
          </tr>
          {% endfor %}
      </tbody>
    </table>  
  </div>
    
{% endblock content %}
    

hecommerce/myadmin/templates/pending-order-detail.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>This is Pending Order Detail </h1>      
  
    <div class="row">
      {% for order in orders %}
      
        <div class="col-lg-8">           
          <button type="button" class="btn btn-primary">{{order.ref_code}}</button>
          
          {% if order.pending == True %}
            <button type="button" class="btn btn-outline-danger" data-ripple-color="dark">
              <a href="{% url 'myadmin:pendingorderreject' order.ref_code %}">
                Reject Order
              </a>
            </button>

            <button type="button" class="btn btn-outline-success" data-ripple-color="dark">
              <a href="{% url 'myadmin:pendingorderconfirm' order.ref_code %}">
                Comfirm
              </a>  
            </button>    
          
            
            <div class="table-responsive">
              <table class="table">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Product Name</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Price</th>
                  </tr>
                </thead>
                <tbody>
                  {% for order_item in order.items.all %}
                  <tr>
                   
                    
                    <th scope="row">1 </th>
                    <td>{{order_item.item.title}}</td>
                    <td>{{order_item.get_total_item}}</td>
                    <td>{{order_item.item.price}}</td>
                           
                  </tr>    
                  {% endfor %} 
                  <tr>
                    {% for my_order in orders %}
                    <td colspan="3"><b>Order Total</b></td>
                    <td><b>${{ my_order.get_total }}</b></td>
                    
                    {% endfor %}
                    
                  </tr>
                </tbody>
              </table>
            </div>

        {% endif %}            
            
        </div>

        <div class="col-lg-4">
          <img src="{{order.payment.payment_img.url}}" alt="" width="500px" height="250px">
        </div>
        
        {% endfor %}

    </div>
    
        
        
{% endblock content %}
    

hecommerce/myadmin/templates/pending-orders.html
{% extends 'base_layout.html' %}

{% block content %}

<div class="table-responsive text-nowrap" style="height: 600px;">

    <table class="table">
      <thead>
        <tr>
          
          <th scope="col">Invoice No</th>
          <th scope="col">Customer Name</th>
          <th scope="col">Quantity</th>          
          <th scope="col">Total</th>
          <th scope="col">Payment Opition</th>
          <th scope="col">Status</th>
          <th scope="col"></th>         
        </tr>
      </thead>
      <tbody>
        {% for order in orders %}
          <tr>  
              <td>
                {{order.ref_code}}
              </td>  

              <td>
                {{order.user}}
              </td>  

              <td>
                {{order.get_item_total}}
              </td> 

              <td>
               $ {{order.get_total}}
              </td> 
                
              <td> 
                  {{order.payment.payment_opition}}       
              </td>                    
              <td>Pending</td>  

              <td>
                <a href="{% url 'myadmin:pendingdetail' slug=order.ref_code %}">
                View Detail
                </a>
              </td>                   
          </tr>          
          {% endfor %}
      </tbody>
    </table>  
  </div>
{% endblock content %}
    

hecommerce/myadmin/templates/update-newsletter.html
{% extends 'base_layout.html' %}

{% block content %}
<div>
    <h3>Update Newsletter</h3>
</div>
<div class="row">
    <div class="col-lg-4">
        <form action="{% url 'myadmin:updatenewsletter' id=newsletter.id%}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div>
                <label for="" class="text-danger">* Title will Not be Shown in User Page</label><br>
                <label for="">Title</label>
                {{form.title}}
            </div>           
            
            <div class="mt-3">
                <label for="" class="">Preferrable Image Dimension 5000px X 550px</label> <br>
                {{form.imge}}
            </div>
            
            <div class="float-right mt-2">
                <input type="submit" name="submit" id="" value="upload" class="btn btn-primary">
            </div>
            
        </form>
    </div>
    <div class="col-lg-4">
        <img src="{{newsletter.imge.url}}" alt="" class="img-thumbnail mt-3">
    </div>
</div>


<script>
    document.getElementById('id_title').className="form-control"
</script>

{% endblock %}

hecommerce/myadmin/templates/update-product-list.html
{% extends 'base_layout.html' %}

{% block content%}
    <h1>Update Product</h1>
    {% for item in object_list %}
    <div class="row">
        <div class="col-lg mb-3 border">
            <div class="row">
                
                    <div class="col">
                    <a href="{% url 'myadmin:updateproduct' slug=item.slug %}">
                        <h5>{{item.title}}</h5> 
                    </a> 
                     </div>

                     <div class="col-lg-1 badge badge-default">
                        <h6>{{item.product_quantity}}</h6>
                        
                    </div>
                
            </div>
            <div class="row">
                <div class="col-lg">
                    {{item.get_category_display}}
                </div>
            </div>
            
        </div>
    </div>
    {% endfor %}
    
{% endblock %}

hecommerce/myadmin/templates/update-product.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Update Product</h1>
    
     <div class="row">         
        <div class="col-md-8">             
            <form action="{% url 'myadmin:updateproduct' slug=item.slug %}" method="POST" class="border border-light p-5 form-container" enctype="multipart/form-data">
                {% csrf_token %}
                 
                <div class="row">
                    <div class="col">
                        <label for="" class="">Title : </label>                    
                        {{form.title}}
                    </div>
                    <div class="col">
                        <label for="" class="">Price :</label>                    
                        {{form.price}}         
                        <p id="error-text" class="text-danger"></p>           
                    </div>
                </div>
                
                <div class="row">
                    <div class="col">
                        <label for="" class="">Slug :</label>                    
                        {{form.slug}}
                    </div>
                    
                    <div class="col">
                        <label for="" class="">Product Qty :</label>                    
                        {{form.product_quantity}}
                        <p id="error-text2" class="text-danger"></p>
                    </div>
                </div>

                <div class="row">
                    <div class="col">
                        <label for="" class="">Description :</label>                    
                        {{form.description}}
                    </div>
                </div>

                <div class="row">
                    <div class="col">
                        <label for="" class="">Category :</label>  
                        {{form.category}}
                    </div>
                    <div class="col">
                        <label for="" class="">Label :</label> 
                        {{form.label}}
                    </div>
                </div>

                <div class="row mt-3">
                    <div class="col">       
                        <p id="error-text1" class="text-danger"></p>                                                         
                        {{form.image}}
                    </div>

                    <div class="col">
                      <label for="" class="text-danger">Product Avaliabality</label>  
                      <div class="custom-form-control">
                        {{form.status}} 
                      </div>
                            
                      
                    </div>
                </div>                

                <div class="float-right mt-2">
                    <a href="{% url 'myadmin:updateproductlist' %}" class="btn btn-danger"> 
                        Cancle
                    </a>
                    <input type="submit" value="Submit" class="btn btn-primary" id="my-button" onclick="checkValidation();">
                </div>
                 
              </form>
        </div>

        <div class="col-md-4">
            <label for="">Current Image : {{item.image}}</label>
            <img src="{{item.image.url}}" alt="" width="500px" height="350px">
        </div>
    </div> 

    <script>   

$(document).ready(function(){
        var _URL = window.URL;
        $("#id_image").change(function (e) {
            if ((file = this.files[0])) {
                img = new Image();                
                 img.onload = function () {
                    if(img.width < 1383 && img.height < 1037){   
                        document.getElementById("error-text1").innerHTML = 'Image Is Too Small. To Upload Please Change Image Dimension';  
                        $('#error-text1').show('slow')                                            
                        $('#my-button').hide('slow')
                    }
                    else if(img.width > 1385 && img.height > 1039){
                        document.getElementById("error-text1").innerHTML = 'Image Is Too Large. To Upload Please Change Image Dimension';  
                        $('#error-text1').show('slow')                                            
                        $('#my-button').hide('slow')
                    }
                    else{
                        $('#error-text1').hide('slow')
                        $('#my-button').show('slow')
                    }
                 };
                img.src = _URL.createObjectURL(file);
            }
            console.log(document.getElementById("id_image"))
        });
    })


    titleInput.addEventListener('keyup', (e) => {
    slugInput.setAttribute('value', slugify(titleInput.value));
    });

        function checkValidation(){ 
                 
            var price = document.getElementById('id_price').value;
            var qty = document.getElementById('id_product_quantity').value;  
                 
            if (isNaN(price) || price < 0){
                $( "form" ).submit(function( event ) {
                event.preventDefault();
                document.getElementById("error-text").innerHTML = 'Price Is Invalid';
                });
            } 
            if (isNaN(qty) || qty < 0){
                $( "form" ).submit(function( event ) {
                event.preventDefault();
                document.getElementById("error-text2").innerHTML = 'Product Quantity Is Invalid';
                });
            }        
        }
    </script>
{% endblock content %}
    