hecommerce/account/urls.py
from django.urls import path
from.views import (
    signup_view,
    login_view,
    logout_view,
    VerificationView,
    superuser_login_view
    
)

app_name = "account"

urlpatterns = [
    path('login/',login_view,name="log_in"),
    path('admin-login',superuser_login_view,name="superuserlogin"),
    path('signup/',signup_view,name="sign_up"),
    path('logout/',logout_view,name="log_out"),
    path('activate/<uidb64>/<token>',VerificationView.as_view(),name="activate")
    
]

hecommerce/core/urls.py
from django.urls import path,re_path
from.views import(
    HomeView,
    ProductDetailView,
    add_to_cart,
    Order_Summary,
    remove_single_item_from_cart,
    remove_from_cart,
    CheckOutView,
    order_snippet_view,
    veiw_ordered_items_lists,
    notifications,
    displayCategory
)

app_name="core"

urlpatterns = [
    path('', HomeView.as_view(),name="productlists"),
    path('order-summary/',Order_Summary.as_view(),name="order-summary"),
    path('check-out/',CheckOutView.as_view(),name="check-out"),
    path('order-snippet/',order_snippet_view,name="order-snippet"),
    path('notifications/',notifications,name="notifications"),
    path('add-to-cart/<slug>/',add_to_cart,name="add-to-cart"), 
    path('remve-from-cart/<slug>/',remove_from_cart,name="remove-from-cart"),
    path('remove-single-item-from-cart/<slug>/',remove_single_item_from_cart,name="remove-single-item-from-cart"),    
    path('view-ordered-items/<slug>/',veiw_ordered_items_lists,name="vieworderedlists"),
    path('category/<category>',displayCategory,name="display-category"),
    re_path(r'(?P<slug>[\w-]+)/$',ProductDetailView.as_view(),name="productdetail"),
    
]

hecommerce/hecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myadmin/',include('myadmin.urls')),
    path('account/',include('account.urls')),
    path('',include('core.urls')),
    
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

hecommerce/account/models.py
from django.db import models

# Create your models here.

hecommerce/account/forms.py
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.models import User

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2']

hecommerce/account/views.py
from django.shortcuts import render,redirect,reverse
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout
from .forms import CreateUserForm
from django.views.generic import View
from django.core.mail import EmailMessage
from django.contrib.auth.models import User
from django.conf import settings
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from .tonken import token_generator
from django.contrib import messages

# Create your views here.
def signup_view(request):
    form = CreateUserForm()
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():              
            input_email = form.cleaned_data.get('email')
            user_mail = User.objects.filter(email=input_email)
            if user_mail.exists():
                messages.warning(request, "Email is already exist")
            else:
                user = form.save(commit=False)
                user.is_active = False
                user.save()
                # paht to view
                # get domain we are on
                # relative url to verfication
                # encode uid
                # token
                uidb64 =urlsafe_base64_encode(force_bytes(user.pk))
                domain = get_current_site(request).domain 
                link =  reverse('account:activate',kwargs={
                    'uidb64':uidb64,'token':token_generator.make_token(user)})
                activate_url = 'http://'+domain+link
                email_subject = 'Activate your account'
                email_body = "Hi" + user.username + "Please Use this link to verify your account\n" + activate_url
                sent_to = form.cleaned_data.get('email')
                email = EmailMessage(
                    email_subject,
                    email_body,
                    settings.EMAIL_HOST_USER,
                    [sent_to]                
                )   
                
                email.send(fail_silently=False)
                form.save()
                return render(request,'acc_activate_email.html')
    
    return render(request,'signup.html',{'form':form})

class VerificationView(View):
    def get(self,request,uidb64,token):
        id = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=id)
        
        if not token_generator.check_token(user,token):
            return redirect('account:log_in')
        if user.is_active:
            return redirect('account:log_in')
        user.is_active = True
        user.save()
        messages.success(request,'Account activated Successfully')
        return redirect('account:log_in')

def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)        
        if form.is_valid():
            user = form.get_user()
            if user.is_superuser:
                messages.warning(request,'Wrong User Name or password')
            else:
                login(request,user)
                return redirect('core:productlists')
    else:
        form = AuthenticationForm
    return render(request,'login.html',{'form':form})

def superuser_login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            if user.is_superuser:                
                login(request,user)
                return redirect('core:productlists')   
            else:
                 messages.warning(request,'Wrong User Name or password')
    else:
        form = AuthenticationForm
    return render(request,'sup-login.html',{'form':form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('core:productlists')
    

hecommerce/account/templates/acc_activate_email.html
{% extends 'base_layout.html' %}


{% block content %}

    <div style="height:500px">
        <h4 class="mt-5">
            Please go to your <a href="http://gmail.com">gamil</a>  to activate account
        </h4>
    </div>
    
{% endblock content %}
    

hecommerce/account/templates/login.html
{% extends 'base_layout.html' %}

{% block content %}

<div class="card mt-3 mb-3 text-center" style="width: 410px;margin: 0 auto;">
    <h3 class="card-header info-color white-text py-3 text-center">Log In</h3>
    <form action="{% url 'account:log_in' %}" method="POST" class="text-center  p-5 mb-3"  style="color: #757575;">
        
        {% csrf_token %}    
        {{form.username}}
        {{form.password}}  
        {% if form.errors %}
        <p class="text-danger">Incorrect Password or user name</p>
        {% endif %}
        <p class="mt-3">Not a Member?<a href="{% url 'account:sign_up' %}">
            Register Here
       </a></p>          
        
        <input type="submit" value="Log In" class="btn btn-primary mt-2">
      
        
    
    </form>
</div>

<script>    
    document.getElementById("id_username").className = "form-control mb-3";  
    document.getElementById("id_username").placeholder = "Enter User Name";    
    document.getElementById("id_password").className = "form-control mt-4";
    document.getElementById("id_password").placeholder = "Enter Password";     
    
    
</script>


{% endblock content %}

hecommerce/account/templates/signup.html
{% extends 'base_layout.html' %}

{% block content %}


<div class="card mt-5 mb-5 text-center" style="width: 410px;margin: 0 auto;">
  <h3 class="card-header text-center text-white info-color">Sign up</h3>
  <form action="{% url 'account:sign_up' %}" method="POST" class="text-center p-5 mb-3" style="color: #757575;">
    {% csrf_token %}
      {{form.username}}
      {{form.email}}
      {{form.password1}}
      {{form.password2}}
      {% if form.errors %}
      <p class="text-dnager">Invalid Form</p>
      {% endif %}
      <p class="mt-3">
        Already have account? <a href="{% url 'account:log_in' %}">
          Login Here
        </a>
      </p>
      <input type="submit" value="Sing Up" class="btn btn-primary mt-2">
  
  </form>
  
</div>
<script>
    document.getElementById("id_username").className = "form-control mb-3";  
    document.getElementById("id_username").placeholder = "Enter User Name"; 
    document.getElementById("id_email").className = "form-control mb-3";  
    document.getElementById("id_email").placeholder = "Enter Your Email"; 
    document.getElementById("id_password1").className = "form-control mt-4";
    document.getElementById("id_password1").placeholder = "Enter Password"; 
    document.getElementById("id_password2").className = "form-control mt-4";
    document.getElementById("id_password2").placeholder = "Retype Password";
</script>

{% endblock content %}

hecommerce/account/templates/sup-login.html
{% extends 'base_layout.html' %}

{% block content %}

<div class="card mt-5 mb-5 text-center " style="width: 410px;margin: 0 auto;">
    <h3 class="card-header info-color white-text py-3 text-center">Auth Log In</h3>
    <form action="{% url 'account:superuserlogin' %}" method="POST" class="text-center  p-5 mb-3"  style="color: #757575;">
        
        {% csrf_token %}    
        {{form.username}}
        {{form.password}}  
        {% if form.errors %}
        <p class="text-danger">Incorrect Password or user name</p>
        {% endif %}      
        
        <input type="submit" value="Log In" class="btn btn-primary mt-2">
      
        
    
    </form>
</div>

<script>    
    document.getElementById("id_username").className = "form-control mb-3";  
    document.getElementById("id_username").placeholder = "Enter User Name";    
    document.getElementById("id_password").className = "form-control mt-4";
    document.getElementById("id_password").placeholder = "Enter Password";         
    
</script>


{% endblock content %}